# Numpy Basic

## The data type

- The data type can be used as the dimension representation.
- Using like the linear equation
- `numpy` package is used to define the linear equations

​	 **note** many data science techniques use the linear equation to manipulate the value.

There are two type of data

**Scalar**

- a number
- no direction



**Vector**

- list of numbers
- identify that point in space
- use as the direction

If we have the point (3,4)

![image-20230731183241242](./assets/image-20230731183241242.png)

* $\overrightarrow{a}$ show the scalar value of the vector

* aka the absolute value

* The dimension may have more than one di### Creating the vector



using the function array which will convert the list to an array

```
import numpy as np
v = np.array ([1.,2.,3.])
```

now v will act as the vector in linear algebra instead of a list

In [1]:
import numpy as np
v = np.array([1.,2.,3.])

### Create the numpy as given

```python
import numpy as np
v1 = np.array([1.,3,-5])
v2 = np.array([4,-2,-1])
```

Then try to draw the 3d image for this vector?

In [2]:
import numpy as np
v1 = np.array([1.,3,-5])
v2 = np.array([4,-2,-1])

Try to guess what is the result of this two command

```python
print (2*v1)
print (v1/2)
```



In [3]:
print (2*v1)
print (v1/2)

[  2.   6. -10.]
[ 0.5  1.5 -2.5]


Try this combination

```python
print(3*v1)
print (v1 + v2)
```

In [4]:
print(3*v1)
print (v1 + v2)

[  3.   9. -15.]
[ 5.  1. -6.]


Try this code
```python
v4 = np.array([1,2,3,4,5])
print (v1 + v4)
```

In [6]:
v4 = np.array([1,2,3,4,5])
print (v1 + v4)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

## Matrix

Matrix is a data structure that consists of rows and columns.

The matrix can be implemented using the numpy

![image-20230731184629040](./assets/image-20230731184629040.png)

<img src="./assets/1024px-Matrix.svg.png" alt="undefined" style="zoom:50%;" />

**Note**

Vectors are no column - and no row matrices

> the $n$ vector, and $n \times 1$ and a $1 \times n$ matrix are three different objects even if they contain the same data.



To create the matrix

using array function, but from the list of the list instead

```python
M = np.array([[1.,2],
              [0.,1]])
M
```

In [7]:
M = np.array([[1.,2],
              [0.,1]])
M

array([[1., 2.],
       [0., 1.]])

#### shape function

To define the number of raw, and column of the matrix

```python
np.shape(M)
```

In [8]:
np.shape(M)

(2, 2)

#### Task

Create this matrix and show the shape of the matrix
$$
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
\end{bmatrix}
$$

In [9]:
N = np.array([[1.,2.,3.,4],
              [5.,6.,7.,8]])
N

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

#### reshape

change the column and matrix

try

```python
K = M.reshape(4,1)
K
```

In [10]:
K = M.reshape(4,1)
K

array([[1.],
       [2.],
       [0.],
       [1.]])

```python
L = M.reshape(1,4)
```

In [11]:
L = M.reshape(1,4)

The reshape matrix should be the same amount of data; otherwise, the error will be occurred.

Try to change your created data to 3*3 matrix from matrix M


Try to make it to 4 x 2 matrix

Try to make it as 2,2,2 matrix

## Using other packages

We can create the files which is contains some function by created `my_funcs.py` and post it near by this code (in the same directory)

```python
def print_a():
    print("a")

def print_b():
    print("b")
```

In [12]:
def print_a():
    print("a")

def print_b():
    print("b")

Then type the code as given

```python
import my_funcs
my_funcs.print_a()
my_funcs.print_b()
```

In [1]:
import my_funcs
my_funcs.print_a()
my_funcs.print_b()

ModuleNotFoundError: No module named 'my_funcs'

### import thechniques

* import module directly
```python
import math
print(math.pi)

In [15]:
import math
print(math.pi)

3.141592653589793



* using static import
> import the function or attribute directly, no need to add the package name when call

```python
from math import pi
# Note that in the above examples,
# we used math.pi. Here we have to used pi direcly.
print(pi)
```

In [2]:
from math import pi
print(pi)

3.141592653589793


* static import to use all methods in the package
```python
from math import *
print(pi)
print(factorial(6))
```

In [4]:
from math import *
print(pi)
print(factorial(6))

3.141592653589793
720


What do we use here?
  ```python
import numpy as np
from scipy.linalg import solve
A = np.array([[1.,2.],[3.,4.]])
b = np.array([1.,4.])
x = solve(A,b)
print(x)
```

In [5]:
import numpy as np
from scipy.linalg import solve
A = np.array([[1.,2.],[3.,4.]])
b = np.array([1.,4.])
x = solve(A,b)
print(x)

[ 2.  -0.5]


# Linear Programming



Using Linear algebra to help people



## Using the Decision support system

- computer-based information system
- supports business or organizational decision-making
- DSS serve the management, operations, and planning level of and organization
- help to make decision
  - of the situation which may be rapidly chaining and not easily specified in advance

## Optimization



- selection of the best elements
- from a set of available alternatives

![image-20230801172230114](./assets/image-20230801172230114.png)

**The best solution**

if we have many relationships

![image-20230801172343701](./assets/image-20230801172343701.png)

### Steps for Formulating and Optimization Model

1. Obtain Data
2. Define the decision variables
3. Define the objective functions (in term of the decision variables)
4. Write the constraints as equalities or inqualities
------

### Characteristics of Linear Programming

- Continuous- valued variables

- No dependence between variables

  - The contribution of each variable to the objective or constraints is independent of that from the other variables

    > NO $x_1 \cdot x_2$

  - The contribution of each variable to the objective or constraints is directly proportional to the variable value

    > No $x^n or \, x^2  \, x^3$

- The model is deterministic

- Not guarantee to get feasible solution

### Example

In the custom-made shirt factory, shirt A and shirt B are produced.

&emsp;Shirt type A

&emsp;&emsp;requires 9 hrs of labor and 12 buttons

&emsp;&emsp;the profit is 350 THB/unit

&emsp;Shirt type B

&emsp;&emsp;requires 6 hours and labor of 16 buttons

&emsp;&emsp;the profit is 300 THB/unit

There are 2880 buttons, 1566 hrs. of labor, and 200 cloths available in the factory

How many type A and type B shirts that the manufacturer should produce?

Try to write the related equations?


#### Step 1

![image-20230801165028646](./assets/image-20230801165028646.png)

#### Step 2

![image-20230801165047841](./assets/image-20230801165047841.png)

#### Step 3

![image-20230801165103187](./assets/image-20230801165103187.png)

#### Step 4

![image-20230801165117222](./assets/image-20230801165117222.png)



#### Step 5

![image-20230801165132452](./assets/image-20230801165132452.png)

#### Step 6

![image-20230801165148808](./assets/image-20230801165148808.png)

#### Step 7

![image-20230801165204453](./assets/image-20230801165204453.png)

#### Step 8

![image-20230801165219675](./assets/image-20230801165219675.png)



## Using Python Linear Programming



Using the pulp component

the given work can be implement with this code

```python
from pulp import *
# create the new problem
prob = LpProblem("Cloth_Problem",LpMaximize)
# add the variable https://www.coin-or.org/PuLP/pulp.html
x1 = LpVariable("Shirt A",lowBound = 0,cat='Integer')
x2 = LpVariable("Shirt B",lowBound = 0,cat='Integer')
# add the constraint
c1 = x1 + x2 <= 200
c2 = 9*x1+6*x2 <= 1566
c3 = 12*x1 + 16*x2 <= 2880
# Objective value
obj = 350*x1 + 300*x2

prob += obj, "Maximum profit"
prob += c1, "The amount of all shirt"
prob += c2, "The labour amount"
prob += c3, "The button amount"

prob.solve()

print("Status:" + LpStatus[prob.status])
for v in prob.variables():
    print (v.name, "=", v.varValue)
for v in prob.constraints:
    print (v)
print ("Total profit is" , value(prob.objective))
print ("Total profit is" , value(prob.objective))
```

**Note** you may not need to type the comments

**Note** you may need to run the command `pip install pulp` to install the pacakge to the run time first.

this is just one implementation of the solution

In [6]:
!pip install pulp


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [7]:
from pulp import *
# create the new problem
prob = LpProblem("Cloth_Problem",LpMaximize)
# add the variable https://www.coin-or.org/PuLP/pulp.html
x1 = LpVariable("Shirt A",lowBound = 0,cat='Integer')
x2 = LpVariable("Shirt B",lowBound = 0,cat='Integer')
# add the constraint
c1 = x1 + x2 <= 200
c2 = 9*x1+6*x2 <= 1566
c3 = 12*x1 + 16*x2 <= 2880
# Objective value
obj = 350*x1 + 300*x2

prob += obj, "Maximum profit"
prob += c1, "The amount of all shirt"
prob += c2, "The labour amount"
prob += c3, "The button amount"

prob.solve()

print("Status:" + LpStatus[prob.status])
for v in prob.variables():
    print (v.name, "=", v.varValue)
for v in prob.constraints:
    print (v)
print ("Total profit is" , value(prob.objective))
print ("Total profit is" , value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/hathaichanokp./Note/venv/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/bef579098e154f7baaa43a19ae99feaf-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/bef579098e154f7baaa43a19ae99feaf-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 21 RHS
At line 25 BOUNDS
At line 28 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 66100 - 0.00 seconds
Cgl0004I processed model has 3 rows, 2 columns (2 integer (0 of which binary)) and 6 elements
Cutoff increment increased from 1e-05 to 49.9999
Cbc0012I Integer solution of -66100 found by DiveCoefficient after 0 iterations and 0 nodes (0.00 seconds)
Cbc00

### Task

**The Ice-cream shop**

Assume you open your ice cream shop, there are only two types of ice cream, vanilla and strawberry. When a box of ice cream is sold, you will get the benefit for $2 for vanilla ice cream and $3 for strawberry ice cream. To make the ice cream, the fresh milk is required. To make a box of vanilla ice cream requires 0.5 liter and strawberry ice cream requires 0.2 liter. You daily order 10 liters of fresh milk. To promote your ice cream shop, you give a doll for each ice cream box. The number of dolls, that you can give to customers, is 30 dolls per day.

So, how many boxes of vanilla ice cream and strawberry ice cream that you would like to produce to get maximum profit ?



In [8]:
from pulp import *
prob = LpProblem("ICECREAMPROBLEM",LpMaximize)
x1 = LpVariable("Vanilla",lowBound = 0,cat='Integer')
x2 = LpVariable("Strawberry",lowBound = 0,cat='Integer')
# add the constraint
c1 = 0.5*x1 + 0.2*x2 <= 10
c2 = x1+x2 <= 30
# Objective value
obj = 2*x1 + 3*x2

prob += obj, "Maximum profit"
prob += c1, "The freshmilk order"
prob += c2, "The dolls"

prob.solve()

print("Status:" + LpStatus[prob.status])
for v in prob.variables():
    print (v.name, "=", v.varValue)
for v in prob.constraints:
    print (v)
print ("Total profit is" , value(prob.objective))
print ("Total profit is" , value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/hathaichanokp./Note/venv/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/08914f1d44a5437e9aa32a81ad5d9a31-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/08914f1d44a5437e9aa32a81ad5d9a31-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 18 RHS
At line 21 BOUNDS
At line 24 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 90 - 0.00 seconds
Cgl0004I processed model has 2 rows, 2 columns (2 integer (0 of which binary)) and 4 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0012I Integer solution of -90 found by DiveCoefficient after 0 iterations and 0 nodes (0.05 seconds)
Cbc0001I Sea

### Portfolio Selection

Maximize the return rate

with the given portfolio

![image-20230801165530908](./assets/image-20230801165530908.png)

With these policies

- Total amount= €90000
- Amount in shares of a sector no larger than50% of total available
- Amount in shares with the larger return of a sector less or equal to 80% of sector’s total amount
- Amount in manufacturing company Β less or equal to 10% of the whole share amount
- Amount in mutual funds less or equal to 25% of the amount in manufacturing shares