# Combine and Merging Datasets

data contained can be combined together in a number of ways



## Database-Style Dataframe joins


The same key data are bound.
Look at the example


In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

```python
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df1
```

In [2]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

```python
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})
df2
```

In [3]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

To merge two Dataframe with the same index 
```python
pd.merge(df1,df2)
```

In [4]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

Without setting anything. The key will used from the columns which is the same name in both data frame. The values which are the same in both data are provided, and the Cartesian products of the other values are provided as the data.

It should be better if we specified the key name

```python
pd.merge(df1,df2,on='key')
```

In [5]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

we can merge on the different column name

```python
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})
```

In [6]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})

### Work
Form the given /file/studentlist.xlsx
It is the Excel which provide the score of the students.
Create the data frame which consist of the total score of Attendance(Midterm) score,and midterm score
-> to get the new dataframe from the old dataframe column you may use this code
` new = old[['A', 'C', 'D']].copy() `
to change the specific column name you may use
` rankings_pd.rename(columns = {'test':'TEST'}, inplace = True)`
note: you do not have to set the student id column to be the index in this work

Check df3 and df4
```python
df3
```

In [7]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

```python
df4
```

In [8]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

then try to merge df3 and df4
```python
pd.merge(df3,df4)
```

In [9]:
pd.merge(df3,df4)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

You may see that it's could not merge as there is no column which are the same key name.
We can specify the column name which can be merge using the different name with the `left-on` and `right_on` argument
```python
pd.merge(df3, df4, left_on='lkey', right_on='rkey')
```

In [10]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

or 
```python
pd.merge(df4, df3,  right_on='lkey',left_on='rkey')
```

In [11]:
pd.merge(df4, df3,  right_on='lkey',left_on='rkey')

rkey  data2 lkey  data1
0    a      0    a      2
1    a      0    a      4
2    a      0    a      5
3    b      1    b      0
4    b      1    b      1
5    b      1    b      6

You may see that c, and d is removed as it's not in the left data frame

To use all data we use the outer argument
```python
pd.merge(df1,df2,how='outer')
```

In [12]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

You may try other argument to see the different
![image-20230915053652812](./assets/image-20230915053652812.png)


inner join is the intersection of the data
```python
pd.merge(df1,df2,how='inner')
```

In [13]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

left join is the left data frame
```python
pd.merge(df1,df2,how='left')
```

In [14]:
pd.merge(df1,df2,how='left')

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

we can merge with multiple keys by passing a list of columns
try to create this given data frame
```python
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
```

In [15]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})

then try to merge with the multiple keys
```python
pd.merge(left,right,on=['key1','key2'],how='outer')
```

In [16]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval  rval
0  bar  one   3.0   6.0
1  bar  two   NaN   7.0
2  foo  one   1.0   4.0
3  foo  one   1.0   5.0
4  foo  two   2.0   NaN

Some time if the name of the column may be collapse. (Same column name, but not the key)
You may change the name of the column before merging directly, or you can set the suffix column
the example of the problem is shown
```python
pd.merge(left, right, on='key1')
```

In [17]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

the suffixes can be set by the `suffixes` argument
```python
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))
```

In [18]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

### Work
The students have been withdrawn so they do not have the score, in addition the staff change some of the index name.
So please try to add the attendance midterm score to the previous pandas


## Merging by index

Some time you may found that the part you want to merge is the index.
You can set the `left_index=True` or `right_index=True` to indicate that you need to use the index as the merge key

try this source code
```python
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
```

In [19]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

then try to merge with the index
```python
pd.merge(left1, right1, left_on='key', right_index=True)
```

In [20]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

the how can be applied as the same as the normal merge
```python
pd.merge(left1, right1, left_on='key', right_index=True,how ='outer')
```

In [21]:
pd.merge(left1, right1, left_on='key', right_index=True,how ='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

With hierarchically index, joining on index can be used as multiple-key merge
```python
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio',
                               'Nevada', 'Nevada'],
                      'key2': [2000, 2001, 2002, 2001, 2002],
                      'data': np.arange(5.)})
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                        index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',
                                'Ohio', 'Ohio'],
                                 [2001, 2000, 2000, 2000, 2001, 2002]],
                        columns=['event1', 'event2'])
 ```

In [22]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio',
                               'Nevada', 'Nevada'],
                      'key2': [2000, 2001, 2002, 2001, 2002],
                      'data': np.arange(5.)})
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                        index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',
                                'Ohio', 'Ohio'],
                                 [2001, 2000, 2000, 2000, 2001, 2002]],
                        columns=['event1', 'event2'])

The merge with multiple column can be set with the column, and the key index
```python
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)
```

In [23]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

with the `outer` join all data will be merged
```python
pd.merge(lefth, righth, left_on=['key1', 'key2'],
         right_index=True, how='outer')
```

In [24]:
pd.merge(lefth, righth, left_on=['key1', 'key2'],
         right_index=True, how='outer')

key1  key2  data  event1  event2
4  Nevada  2000   NaN     2.0     3.0
3  Nevada  2001   3.0     0.0     1.0
4  Nevada  2002   4.0     NaN     NaN
0    Ohio  2000   0.0     4.0     5.0
0    Ohio  2000   0.0     6.0     7.0
1    Ohio  2001   1.0     8.0     9.0
2    Ohio  2002   2.0    10.0    11.0

### Work
now setting the index to the Dataframe which we have done so far.
then add the rest of the score so that we can handle the overall score with in Dataframe

Now find the name of the students whose name is in the top 10 of the total score.

## Concatenating Along an Axis

Concatenating data is to concat data to the same data.

An Axis mean concat the column data

In NumPy concatenate data concate it in each columns as shown in example

```python
arr = np.arange(12).reshape((3, 4))
arr
```

In [25]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

We can concat the arrays by using the `np.concatenate` function
```python
np.concatenate([arr, arr])
```

In [26]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

we can concatenate the array in the different axis by passing the axis argument
```python
np.concatenate([arr, arr], axis=1)
```

In [27]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In Pandas, there are many concerns before concatination

* If the objects are indexed differently on the other axes, should we combine the distinct elements in these axes or use only the shared values (the intersection)?
* Do the concatenated chunks of data need to be identifiable in the resulting object?
* Does the “concatenation axis” contain data that needs to be preserved? In many cases, the default integer labels in a DataFrame are best discarded during concatenation.

try creating a series

```python
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
```

In [28]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

Then try the simple concat
```python
pd.concat([s1, s2, s3])
```

In [29]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

and then concat on Axis
```python
pd.concat([s1, s2, s3], axis=1)
```

In [30]:
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

You may name each of the columns by the key column
```python
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])
```

In [31]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

You may notice that each series are concat as a new column.

This we can say as the union case as the data that combined all data (and NaN has been added to complete the data series)

To intersect them, you may passing `join='inner'`

see the following example
```python
s4 = pd.concat([s1, s3])
s4
```

In [32]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

if we concat in the different axis
```python
pd.concat([s1, s4], axis=1)
```

In [33]:
pd.concat([s1, s4], axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

then try the inner join
```python
pd.concat([s1, s4], axis=1, join='inner')
```

In [34]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

we can provide the hierarchical index of the search as given
```python
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result
```




In [35]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

we also use the unstack() to show all data
```python
result.unstack()
```

In [36]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

### Work
It's happen that there are other sections score in the class. The files/studentlist2.xlsx provide the score for the second section. merge the data from two file to only one dataframe to find out the descriptive statistic of all the students.

The teacher is very funny, they will random the score for all the students, create a new dataframe which provide the random score from 1 to the maximum score we can get from all students.
then merge the score to the student, and calculate the new score of all the student. then set the grade of the student by who get the grade less than 80 will get `F` otherwise will get `A`

## Combine Data with Overlap



The data con be merse if there are overlap in full or part

In [37]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e', 'd', 'c', 'b', 'a'])

Combine the series using the if else expression.
Let's try
```python
np.where(pd.isnull(a),b,a)
```

In [38]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, 5. ])

try vice versa
```python
np.where(pd.isnull(a),a,b)
```

In [39]:
np.where(pd.isnull(a),a,b)

array([nan,  1., nan,  3.,  4., nan])

`combine_first` combine the data the series
```python
b[:-2].combine_first(a[2:])
```

In [40]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

`combine_first` for the Dataframe will do the same thing but with all column by column.

It is similar to *patching* the data (replace the data in `NaN` position.

In [41]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
 'b': [np.nan, 2., np.nan, 6.],
 'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
 'b': [np.nan, 3., 4., 6., 8.]})
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

try
```python
df1.combine_first(df2)
```


In [42]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

```python
df2.combine_first(df1)
```

In [43]:
df2.combine_first(df1)

a    b     c
0  5.0  NaN   2.0
1  4.0  3.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# Reshaping and Pivoting



## Reshaping with Hierachical Indexing

Using the Hierarchical Indexing can reshape data in different way

The operations we can use are



*   `stack` rotate or pivots from the columns in the data to the rows
*   `unstack` privots from the rows into the columns



In [44]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
    index=pd.Index(['Ohio', 'Colorado'], name='state'),
    columns=pd.Index(['one', 'two', 'three'],
    name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

Using the `stack` to pivot the columns into the rows, produce a serie from the data frame



```python
result = data.stack()
result
```

In [45]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

from hierachically indexed Series, we can rearrange into a DataFrame with `unstack`
```python
result.unstack()
```

In [46]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

By the default the innermost level is unstacked, we can unstadck the different level by pasing the level name.
```python
result.unstack('state')
```

In [47]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

unstack may introduce the missing data if all of the value in the level is ont found in each group

In [48]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

try to do unstack
```python
data2.unstack()
```

In [49]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

Stacking filter out the missing data by default, to preseved the na when unstack `dropna=False ` is required
```python
data2.unstack().stack()
```

In [50]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

when using the dropna
```python
data2.unstack().stack(dropna=False)
```

In [51]:
data2.unstack().stack(dropna=False)

/var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/ipykernel_29387/1518106626.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data2.unstack().stack(dropna=False)


one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

When you unstack in a DataFrame, the **level unstacked** becomes the lowest level in the result
```python
df = pd.DataFrame({'left': result, 'right': result + 5},
                  columns=pd.Index(['left', 'right'], name='side'))
df
```

In [52]:
df = pd.DataFrame({'left': result, 'right': result + 5},
                  columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

try
```python
df.unstack('state')
```

In [53]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

we may use the state to stack the side
```python
df.unstack('state').stack('side')
```

In [54]:
df.unstack('state').stack('side')

/var/folders/q2/n7kvrhfn6pl7tqqhzw_fjwn40000gn/T/ipykernel_29387/3494443071.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack('state').stack('side')


state         Ohio  Colorado
number side                 
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

# Work

From the three files provided [here](https://github.com/jakevdp/data-USstates/)

1. Bind all data to get the data frame which have the state/ abbreviation, and area(sq.mi)
2. Bind the data to get the State, age, and population
3. Create the multiple hierachy dataframe, which contains the age as sub hierachy. The column should be the year and population, and the year must be order.


1. Bind all data to get the data frame which have the state/ abbreviation, and area(sq.mi)

2. Bind the data to get the State, age, and population

3. Create the multiple hierachy dataframe, which contains the age as sub hierachy. The column should be the year and population, and the year must be order.